WIP: Substitute unwrap for ? operator
uuid-rs/uuid pull request #466
Opened 2020-03-15 20:03 UTC by amadeusine

**I'm submitting a** refactor (and fixes for test cases).

# Description

This PR addresses C-QUESTION-MARK in the roadmap for #191. The examples have been updated to accommodate for the `?` operator instead of `.unwrap` or `try!`.

# Motivation

UUID can move forward with other portions of documentation given this has been completed.

# Tests

All existing tests remain successful after changes.

# Related Issue(s)

#191

2020-03-15 23:58 UTC, Dylan-DPC submitted a review, later dismissed

2020-03-15 23:58 UTC, Dylan-DPC commented
bors: r+

2020-03-16 00:47 UTC, Dylan-DPC commented
@kinggoesgaming can you check the travis configuration if you have time? thanks

2020-08-12 20:47 UTC, kinggoesgaming commented
bors try

2020-08-16 01:19 UTC, kinggoesgaming commented
An update: I have been trying to get the one heck of a mess that is our build system fixed. This might take sometime to get fixed. I want a good fix not just a system held together with duct tape.

2020-09-05 21:38 UTC, kinggoesgaming submitted a review, later dismissed
Thank you for the PR and sorry for the long wait

2020-09-05 23:56 UTC, kinggoesgaming requested changes
Hey

If you can get the changes made, I will get the PR merged

2020-09-05 23:56 UTC, kinggoesgaming commented on src/lib.rs
>  //!     let my_uuid = Uuid::new_v4()?;
```suggestion
//!     #[cfg(feature = v4")] {
//!         let my_uuid = Uuid::new_v4()?;
//!         println!("{}", my_uuid);
//!    }
```

2020-09-05 23:56 UTC, kinggoesgaming commented on src/lib.rs
>  //!     println!("{}", my_uuid);
```suggestion
```

2020-09-08 20:08 UTC, amadeusine commented
Oops, prematurely pushed here. I'll fix it on my end.

2020-09-09 08:10 UTC, kinggoesgaming commented
No probs just ping when you are ready

2020-09-15 19:16 UTC, kinggoesgaming commented
@amadeusine any update?

2020-09-20 02:51 UTC, amadeusine commented
Update on the changes in question: It looks like the v4 example will not pass tests under `--all-features` as 
`let my_uuid = Uuid::new_v4()?;` propagates `getrandom::Error` (which doesn't impl `std::error::Error` unless enabled). While it is possible to explicitly specify `fn main() -> Result<(), getrandom::Error>`, doing so would then fail on tests with `--no-default-features` due to getrandom being optional.

If either is acceptable, I can go ahead and push. Suggestions welcome.

2020-09-21 01:06 UTC, kinggoesgaming commented
I think the best course of action would be to change to `ignore,rust` to ignore the test for now. The error type is expected to have changes and I think we can cover it under it.

2020-09-22 16:06 UTC, amadeusine commented
It looks like the last change to the ignored example was already merged. Would it be fine to close the PR, then?

2020-10-17 03:10 UTC, kinggoesgaming approved these changes

2020-11-06 03:39 UTC, KodrAus commented
bors r+

2020-11-06 03:58 UTC, merged